# ----
# Site

title: Academy Dev Wiki
description: Academy Dev
url: https://academy.aquaclouds.ru/
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  api:
    title: База данных
    position_number: 1
  admin:
    title: Admin
    position_number: 2
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true
  -
    scope:
      type: "admin"
    values:
      _hide_content: true      

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - function

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
